# Generated by Django 4.1.5 on 2023-01-16 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gos_Number',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('number', models.CharField(max_length=6, verbose_name='Гос. номер авто')),
            ],
        ),
    ]
