# Generated by Django 4.1.5 on 2023-01-18 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GosNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Id')),
                ('number', models.CharField(max_length=6, verbose_name='Гос. номер авто')),
            ],
            options={
                'verbose_name': 'Гос. номер',
                'verbose_name_plural': 'Гос. номера',
            },
        ),
    ]
