# Generated by Django 4.1.5 on 2023-01-16 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gos_number',
            options={'verbose_name': 'Гос. номер', 'verbose_name_plural': 'Гос. номера'},
        ),
        migrations.AlterField(
            model_name='gos_number',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
    ]
