# Generated by Django 4.1.5 on 2023-02-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gosnumber',
            name='number',
            field=models.CharField(max_length=6, unique=True, verbose_name='Гос. номер авто'),
        ),
    ]
