# Generated by Django 4.1.5 on 2023-01-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0002_alter_gos_number_options_alter_gos_number_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gos_Number',
            new_name='GosNumber',
        ),
    ]
